apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: ubuntu
      command: ['sh','-c','while true; do echo "This is configmap Example. Hello $username">>/opt/krish.txt;sleep 10; done']
      volumeMounts:
        - mountPath: /opt/
          name: prash
      env:
        # Define the environment variable
        - name: username
                                     # from the key name in the ConfigMap.
          valueFrom:
            configMapKeyRef:
              name: myconfigmap           # The ConfigMap this value comes from.
              key: name # The key to fetch.
  volumes:
  - name: prash
    configMap:
      name: myconfigmap
      items:
      - key: "place"
        path: "place" 