apiVersion: v1
kind: Pod
metadata:
  name: my-mysql-pod
spec:
  containers:
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-mysql-secret
              key: MYSQL_ROOT_PASSWORD