apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-pod
  name: pod-affinitywrong
spec:
  containers:
  - image: nginx
    name: my-pod
  affinity: 
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: env
                operator: In 
                values: 
                - kris