apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-pod
  name: my-pod
spec:
  containers:
  - image: nginx
    name: my-pod
  nodeName: "gke-scheduling-scheduling-nodes-8d3e498c-r626" 

