apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
spec:
  containers:
    - name: demo
      image: ubuntu
      command: ['sh','-c','while true; do echo "This is configmap Example. Hello $USER_NAME and your password is $PASSWORD">>/opt/krish.txt;sleep 10; done']
      env:
        # Define the environment variable
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: USER_NAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: PASSWORD