apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-pod
  name: taint-redpod
spec:
  containers:
  - image: nginx
    name: my-pod
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: dc
              operator: In
              values:
                - hyd          
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 70
          preference:
            matchExpressions:
              - key: env
                operator: In 
                values: 
                - prd
        - weight: 50
          preference:
            matchExpressions:
              - key: env
                operator: In 
                values: 
                - test
  tolerations:
    - key: color
      operator: Equal
      value: red
      effect: NoSchedule